# Generated by Django 5.0.14 on 2026-08-08 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_asset_is_active_asset_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('breach', 'Breach / Incident'), ('grievance', 'Grievance')], max_length=16)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], default='reported', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, help_text='Complainant email for a grievance, or reporting staff/system for a breach.', max_length=255)),
                ('region', models.CharField(blank=True, max_length=16)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.organization')),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['organization', 'case_type', 'status'], name='cases_case_organiz_246606_idx')],
            },
        ),
    ]
