# Generated by Django 5.0.14 on 2026-08-08 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('core', '0002_asset_is_active_asset_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachNotificationObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('regulator', 'Regulator'), ('data_subject', 'Data Subject(s)'), ('vendor', 'Vendor')], max_length=16)),
                ('recipient_identifier', models.CharField(blank=True, help_text='e.g. the specific authority or vendor name.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('not_required', 'Not Required')], default='pending', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_obligations', to='cases.case')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_notification_obligations', to='core.organization')),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['organization', 'case', 'status'], name='cases_breac_organiz_a7bc2d_idx')],
            },
        ),
    ]
