# Generated by Django 5.0.14 on 2026-08-08 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_asset_is_active_asset_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('cookie_policy', 'Cookie Policy')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('change_summary', models.TextField(blank=True, help_text='What changed from the previous version.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_notices', to='core.organization')),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['organization', 'notice_type', 'status'], name='notices_pri_organiz_05c32e_idx')],
            },
        ),
    ]
