# Generated by Django 5.0.14 on 2026-08-07 23:15

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Set false to revoke this asset's public_key immediately."),
        ),
        migrations.AddField(
            model_name='asset',
            name='public_key',
            field=models.CharField(default=apps.core.models.generate_asset_public_key, editable=False, help_text='Non-secret identifier embedded in the client-side consent SDK.', max_length=64, unique=True),
        ),
    ]
