import { Link } from 'react-router-dom'

import { LegalPageLayout, LegalSection } from '@/components/marketing/LegalPageLayout'
import { APP_NAME } from '@/lib/brand'

export function PrivacyPolicyPage() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="August 8, 2026">
      <LegalSection heading="1. Introduction">
        <p>
          This Privacy Policy explains how {APP_NAME}, Inc. ("{APP_NAME}", "we", "us") collects, uses, and
          shares personal data when you visit this site, use our staff console, or interact with a consent
          banner or rights portal we operate on behalf of a customer.
        </p>
      </LegalSection>

      <LegalSection heading="2. Information We Collect">
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <span className="font-medium text-neutral-800">Account data</span> — name and email address for
            staff who sign in to the administration console.
          </li>
          <li>
            <span className="font-medium text-neutral-800">Consent &amp; request records</span> — the
            purpose-level decisions and data-subject requests our customers' visitors submit through our
            embeddable components.
          </li>
          <li>
            <span className="font-medium text-neutral-800">Usage data</span> — standard technical logs (IP
            address, browser, timestamps) generated by using the Service.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. How We Use Information">
        <p>
          We use this information to operate the Service, authenticate staff accounts, maintain an audit trail
          of consent and rights activity, respond to support requests, and meet our own legal obligations.
        </p>
      </LegalSection>

      <LegalSection heading="4. Cookies &amp; Tracking Technologies">
        <p>
          This site uses only strictly necessary cookies for session and authentication purposes. The consent
          banner and preference center shown on our{' '}
          <Link to="/demo" className="text-indigo-600 hover:underline">
            demo page
          </Link>{' '}
          is the same component our customers embed on their own sites — it is how you would manage optional
          cookies for a site using {APP_NAME}.
        </p>
      </LegalSection>

      <LegalSection heading="5. How We Share Information">
        <p>
          We do not sell personal data. We share it only with subprocessors who help us operate the Service
          (e.g. hosting providers), under contractual confidentiality obligations, or when required by law.
        </p>
      </LegalSection>

      <LegalSection heading="6. Data Retention">
        <p>
          Consent and request records are retained for as long as our customer's account is active, plus a
          period required to demonstrate historical compliance. Account data is deleted within a reasonable
          period after account closure.
        </p>
      </LegalSection>

      <LegalSection heading="7. Your Rights">
        <p>
          Depending on your location, you may have the right to access, correct, delete, or export your
          personal data, or to withdraw consent previously given. You can submit any of these requests
          directly through our{' '}
          <Link to="/rights" className="text-indigo-600 hover:underline">
            data-subject rights portal
          </Link>
          , the same workflow our customers' end users use.
        </p>
      </LegalSection>

      <LegalSection heading="8. International Data Transfers">
        <p>
          Personal data may be processed in countries other than your own. Where required, we rely on
          appropriate safeguards, such as standard contractual clauses, for such transfers.
        </p>
      </LegalSection>

      <LegalSection heading="9. Security">
        <p>
          We use encryption in transit and at rest, role-based access control, and an immutable audit log for
          all data covered by this policy. No method of transmission or storage is 100% secure, and we cannot
          guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection heading="10. Children's Privacy">
        <p>The Service is not directed to children and we do not knowingly collect their data.</p>
      </LegalSection>

      <LegalSection heading="11. Changes to This Policy">
        <p>
          We may update this policy from time to time. Material changes will be reflected by the "Last
          updated" date above.
        </p>
      </LegalSection>

      <LegalSection heading="12. Contact Us">
        <p>Questions about this policy can be sent to privacy@consentra.example (placeholder contact).</p>
      </LegalSection>
    </LegalPageLayout>
  )
}
