# Generated by Django 5.0.14 on 2026-08-07 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_asset_is_active_asset_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSARRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_key', models.CharField(help_text='Verified subject identifier (typically an email).', max_length=255)),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('correction', 'Correction'), ('deletion', 'Deletion'), ('portability', 'Portability'), ('restriction', 'Restriction / Opt-out'), ('consent_withdrawal', 'Consent Withdrawal'), ('processing_info', 'Information About Processing')], max_length=32)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('identity_verification', 'Identity Verification'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=32)),
                ('region', models.CharField(max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsar_requests', to='core.organization')),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='rights_dsar_organiz_874c01_idx'), models.Index(fields=['organization', 'subject_key'], name='rights_dsar_organiz_5c2dfc_idx')],
            },
        ),
    ]
