# Generated by Django 5.0.14 on 2026-08-07 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_key', models.CharField(help_text='Anonymous device/cookie id, or a verified subject identifier.', max_length=255)),
                ('region', models.CharField(max_length=16)),
                ('framework', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='core.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='core.organization')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_essential', models.BooleanField(default=False, help_text='Essential purposes are always granted and cannot be denied.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted', models.BooleanField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='consent.consentrecord')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='consent.purpose')),
            ],
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['organization', 'subject_key', '-version'], name='consent_con_organiz_d61217_idx'),
        ),
        migrations.AddConstraint(
            model_name='purpose',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_purpose_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='consentdecision',
            constraint=models.UniqueConstraint(fields=('record', 'purpose'), name='unique_decision_per_record_purpose'),
        ),
    ]
