# Generated by Django 5.0.14 on 2026-08-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpose',
            options={'ordering': ['code']},
        ),
    ]
