# Generated by Django 5.0.14 on 2026-08-08 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consent', '0002_alter_purpose_options'),
        ('core', '0002_asset_is_active_asset_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('legal_basis', models.CharField(choices=[('consent', 'Consent'), ('contract', 'Contract'), ('legal_obligation', 'Legal Obligation'), ('vital_interests', 'Vital Interests'), ('public_task', 'Public Task'), ('legitimate_interests', 'Legitimate Interests')], max_length=32)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('data_categories', models.TextField(blank=True, help_text='e.g. contact info, financial, health.')),
                ('data_subject_categories', models.TextField(blank=True, help_text='e.g. employees, customers.')),
                ('recipients', models.TextField(blank=True, help_text='Who this data is shared with, if anyone.')),
                ('retention_period', models.CharField(blank=True, max_length=255)),
                ('security_measures', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, help_text='Team or role accountable for this activity.', max_length=255)),
                ('third_country_transfer', models.BooleanField(default=False)),
                ('transfer_safeguards', models.CharField(blank=True, help_text='e.g. SCCs, adequacy decision — required if transfer is true.', max_length=255)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_activities', to='core.organization')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_activities', to='consent.purpose')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_activities', to='core.workspace')),
            ],
            options={
                'ordering': ['review_due_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='ropa_proces_organiz_7b4e31_idx')],
            },
        ),
    ]
